### ISSUE TITLE
Is it supposed to work with MariaDB too?

### ISSUE THREAD

**Issue by j75** [BMDan/tuning-primer.sh#10]
...because it displays the message `The slow query log is NOT enabled.` although *it is*:
```
MariaDB [mysql]> show variables like 'slow_query%';
+---------------------+---------------------------------+
| Variable_name       | Value                           |
+---------------------+---------------------------------+
| slow_query_log      | ON                              |
| slow_query_log_file | /var/log/mysql/mariadb-slow.log |
+---------------------+---------------------------------+
2 rows in set (0.005 sec)
```
There is no variable like `log%queries` as is in the script (maybe it is MySQL specific?).

**Comment by BMDan** [comment]
> There is no variable like log%queries as is in the script (maybe it is MySQL specific?).

Ah, no, this is an artifact.  Old versions of MySQL called this `log_slow_queries`, then it got turned into `slow_query_log`.  Thanks for the report; I'll fix it.

**Comment by BMDan** [comment]
I mean, I _did_ warn you: https://github.com/BMDan/tuning-primer.sh/commit/a998f5f3#diff-77790f49b6076f9f9e79fc20627c1e28R517
