### ISSUE TITLE
Unstable detection of InnoDB

### ISSUE THREAD

**Issue by martinnj** [BMDan/tuning-primer.sh#12]
- Script version: [d79d662e](https://github.com/BMDan/tuning-primer.sh/commit/d79d662eca7056c668c802bdd183d07c1bc0993d)
- MySQL Version: 5.5.64-MariaDB
- Issue: InnoDB state is not detected correctly, resulting in an error: `./tuning-primer.sh: line 1273: *100/: syntax error: operand expected (error token is "*100/")`
- Setup: InnoDB is disabled using `skip-innodb` in `my.cnf`, `tuning-primer` is run as root in default mode.

The issue seems to be that the script uses the `ignore_builtin_innodb` variable to determine whether or not InnoDB is running, this doesn't seem to be reliable for our version at least.

```
MariaDB [(none)]> SHOW VARIABLES LIKE '%innodb%';
+-----------------------+----------+
| Variable_name         | Value    |
+-----------------------+----------+
| have_innodb           | DISABLED |
| ignore_builtin_innodb | OFF      |
+-----------------------+----------+
```

**Comment by BMDan** [comment]
How does [this bug](http://bugs.mysql.com/59393) keep appearing!?  Grumble, grumble.

Anyway, take a look at the attached PR, @martinnj, and let me know if it addresses your issue.

**Comment by martinnj** [comment]
Hi @BMDan 
I've been checking the patched version out on a couple of different configs in dev, seems to solve the issue for me. 👍
