### ISSUE TITLE
Compatibility with MySQL databases in Azure and AWS

### ISSUE THREAD

**Issue by lahmhub** [BMDan/tuning-primer.sh#13]
Databases in the cloud don't use sockets which makes this awesome tool unusable. Azure database for MySQL be created uses the format username@hostname for username, everything else is the same as connecting to a remote server.

**Comment by chrislp** [comment]
This is not an issue related to Azure or AWS, but rather the connection method. You need to connect to a (remote) host instead of a socket.
According to #8 that should be possible by just adding `host=hostname.dhexs74gs2d.region.rds.amazonaws.com` along with the credentials to the local `.my.cnf`.

I tried that, but it doesn't seem to work - tuning primer will always try to connect to a local socket.    
@BMDan do I overlook something or is the version you were referring to at #8 not yet available?

**Comment by BMDan** [comment]
@chrislp is correct that there's no particular reason the script will care whether the database is local, remote, or something else entirely.  As I cautioned in #8, it does measure some things on the current system ([memory, for example](https://github.com/BMDan/tuning-primer.sh/blob/d79d662eca7056c668c802bdd183d07c1bc0993d/tuning-primer.sh#L1419)), so its output may be a bit wonky for remote servers.

Can you share an example of `mysql` with no arguments working to connect to a cloud instance, but this script failing?  (In other words, with a suitably configured `~/.my.cnf`.  Bonus points if you can share the example invoked with `bash -x`; just remember to sanitize your password(s).)

**Comment by chrislp** [comment]
Hi @BMDan thanks for your reply. This is an example of invoking mysql from the bash (I removed some lines for a better overview):

```
$ mysql
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 6811174
Server version: 8.0.23 Source distribution

mysql> show databases;
7 rows in set (0.00 sec)
```

And my `.my.cnf`:

```
$ cat ~/.my.cnf
[client]
host=[databse-id].eu-central-1.rds.amazonaws.com
user=chris
password=[secret]
default-character-set=utf8
```

And this is the output of the tuning primer:
```
$ scripts/tuning-primer.sh
No valid socket file "" found!
The mysqld process is not running or it is installed in a custom location.
If you are sure mysqld is running, execute script in "prompt" mode or set
the socket= variable at the top of this script
```

It looks to me if tuning primer always tries to access a socket, which does not exist in my case.
