### ISSUE TITLE
Suggestion: enclosing password

### ISSUE THREAD

**Issue by Echron** [BMDan/tuning-primer.sh#20]
I was unable to connect when passing on my password (both CLI and my.cnf). I assumed this was because I have an # or @ in the password. I don't see why it went wrong when I passed the password during CLI, this might be a bug but it might be good to document (if it isn't already) that it's better to enclose passwords with certain characters with quotes (as that seems to do the trick)

**Comment by BMDan** [comment]
TIL something about MySQL's handling of options file entries.  I've applied a patch that I believe will resolve the issue.  Please test and let me know.
