### ISSUE TITLE
Syntax error at Line 40

### ISSUE THREAD

**Issue by andisugandi** [BMDan/tuning-primer.sh#22]
Downloading the [tuning-primer.sh](https://raw.githubusercontent.com/BMDan/tuning-primer.sh/master/tuning-primer.sh) as instructed.

But failed when trying to run it:

`$ sh tuning-primer.sh `

The output:
`tuning-primer.sh: 40: Syntax error: "(" unexpected`

Using:
```
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.4 LTS
Release:	20.04
Codename:	focal
```

What do you suggest?

**Comment by raramuridesign** [comment]
@BMDan Is there a solution to this. I get the same error on 
- ubuntu 20.x
- mariadb

**Comment by lint-ai** [comment]
The `sh` command is often a very small subset of a "proper" shell.  Please run it using bash, which can be accomplished with either of the following:

```
bash tuning-primer.sh
```

or

```
chmod +x tuning-primer.sh
./tuning-primer.sh
```

Let me know if that resolves the issue for you.

**Comment by BMDan** [comment]
@raramuridesign / @andisugandi , please reopen this issue if it still happens when running in a proper `bash` (as opposed to `sh`) environment.
