### ISSUE TITLE
Error: Command line calculator 'bc' not found!

### ISSUE THREAD

**Issue by lekiend** [BMDan/tuning-primer.sh#28]
Hello,

When I run your script on Debian 9 with MariaDB 10.5, I get the following error:

> Error: Command line calculator 'bc' not found!

mysqltuner works perfectly.

Regards

**Comment by CLechleitner42** [comment]
Am 24.02.23 um 00:44 schrieb lekiend:
> Hello,
> 
> When I run your script on Debian 9 with MariaDB 10.5, I get the following error:
> 
>     Error: Command line calculator 'bc' not found!

Install bc then.

sudo apt install -y bc


Regards, Christoph


-- 

Christoph Lechleitner

Geschäftsführung

------------------------------------------------------------------------
ITEG IT-Engineers GmbH | Salurner Straße 18, A-6020 Innsbruck
FN 365826f | Handelsgericht Innsbruck | Mobiltelefon: +43 676 3674710
Mail: ***@***.*** | Web: http://www.iteg.at/
------------------------------------------------------------------------
