### ISSUE TITLE
InnoDB detection fails for 5.7 and above

### ISSUE THREAD

**Issue by kzalewski** [BMDan/tuning-primer.sh#3]
This script needs a simple update to handle InnoDB detection for MySQL 5.7 and above.  The current logic does not look for 5.7, and therefore sets innodb_enabled to 0 instead of 1.

**Comment by BMDan** [comment]
Thanks for the report!

Fixed in https://github.com/BMDan/tuning-primer.sh/commit/651ad169633404ef3cd9e2b1a233f6c3ff6d7f1f .
