### ISSUE TITLE
Support for Mysql 8

### ISSUE THREAD

**Issue by kkmuffme** [BMDan/tuning-primer.sh#8]
Are there any plans to support Mysql 8?

Currently it fails with "INITIAL LOGIN ATTEMPT FAILED" (respectively FINAL LOGIN ATTEMPT FAILED)

**Comment by BMDan** [comment]
WFM with MySQL 8 now.  Please test and confirm.

**Comment by kkmuffme** [comment]
Now having this error when I select to create the my.cnf

tuning-primer.sh: line 118: ~/.my.cnf: No such file or directory
- FINAL LOGIN ATTEMPT FAILED -

but even when I type N, it will fail (but without the above line 118 error)

Is it possible to login via TCP instead of socket too?

**Comment by BMDan** [comment]
> `tuning-primer.sh: line 118: ~/.my.cnf: No such file or directory`

Oops.  Fixed.

> Is it possible to login via TCP instead of socket too?

Sure, but that will require you to roll your own `.my.cnf`.  Something like:

```ini
[client]
host=127.0.0.1
user=mark
password=e5p0nd4
```

Note the old trickiness about `host` applies here: `localhost` and `127.0.0.1` mean different things.  If you want to force TCP, use the latter.  Of course, if your DB host isn't the same as the host on which you're running this script, modify things accordingly, but be forewarned that this script occasionally makes assumptions about the environment in which it's running based on the host on which it's launched.

**Comment by kkmuffme** [comment]
Thanks, but boesn't work. It still asks for it/sock.

What I did:

```
wget https://raw.githubusercontent.com/BMDan/tuning-primer.sh/master/tuning-primer.sh
vi .my.cnf
```

then filled in the .my.cnf as your example above (but with my user/pw) & save it.
It still checks .sock only, like if I didn't create this file at all.
Only in the last step, where it asks if it should create a .my.cnf it fails when I press "y", since an .my.cnf already exists.

**Comment by BMDan** [comment]
@kkmuffme First, make the `mysql` command work.  Once that works, this script will work.

Alternatively, set a temporary password, and then run this command with `bash -x ./tuning-primer/tuning-primer.sh` and share the output here.  I'm almost certain that the issue either your configuration or your input, but the script should try to provide as much guidance as it can towards resolving (or at least identifying) those issues.

**Comment by yongsr** [comment]
I also having the same issue even after I created the .my.cnf file. I am runningon Centos 7

- FINAL LOGIN ATTEMPT FAILED -
Unable to log into socket: /var/lib/mysql/mysql.sock

**Comment by BMDan** [comment]
_@yongsr wrote:_
> I also having the same issue even after I created the .my.cnf file. I am running on Centos 7 with Mysq1 5.7.26

Does the `mysql` command work without any other arguments?  If it doesn't, nor will this.

The script tries to make some good guesses about your connection preferences, but if it can't prompt its way to success, then configuring `${HOME}/.my.cnf` such that `mysql` works should always result in this script working as well.  If `mysql` works and this command doesn't, please share your `.my.cnf` and the full output of the script (after X-ing out all passwords, of course).

**Comment by yongsr** [comment]
> _@yongsr wrote:_
> 
> > I also having the same issue even after I created the .my.cnf file. I am running on Centos 7 with Mysq1 5.7.26
> 
> Does the `mysql` command work without any other arguments? If it doesn't, nor will this.
> 
> The script tries to make some good guesses about your connection preferences, but if it can't prompt its way to success, then configuring `${HOME}/.my.cnf` such that `mysql` works should always result in this script working as well. If `mysql` works and this command doesn't, please share your `.my.cnf` and the full output of the script (after X-ing out all passwords, of course).

it requires mysql -uuser -p to work

**Comment by kkmuffme** [comment]
OK thanks, finally got it working.

```
# get in the current users home directory, as this is where mysql checks the .my.cnf
cd
vi .my.cnf
# make sure the file contains: (without leading #, with your values obviously)
#[client]
#host=127.0.0.1
#port=3306
#user=myuser
#password="mypassword"
# save the file
wget https://raw.githubusercontent.com/BMDan/tuning-primer.sh/master/tuning-primer.sh
bash tuning-primer.sh
```

Note: If you are mainly using InnoDB tables, some suggestions of tuning primer (e.g. table_open_cache) are useless & can be ignored.

**Comment by BMDan** [comment]
`table_open_cache` is still relevant in InnoDB (though if you aren't running with `innodb_file_per_table`, it's admittedly _far less_ relevant).  The heuristic the script uses looks at `opened_tables`, so if it's recommending an expansion of the cache, it's because you're churning `fd`s.  Don't do that; `fd`s are cheap, but opening and closing them isn't.

**Comment by kkmuffme** [comment]
@BMDan isn't it only using innodb_open_files with innodb?

**Comment by BMDan** [comment]
> @BMDan isn't it only using innodb_open_files with innodb?

They are different settings, but both are used (even in InnoDB-only servers), and both should be configured correctly.

But let's break this out to a separate issue; if you think the script should recommend different settings, that's separate from whether it works on MySQL 8.  :)
